[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Gleb-Pinchuk <ghliebp@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
python-dotenv = "^1.2.1"


[tool.poetry.group.dev.dependencies]
types-requests = "^2.32.4.20250913"
types-psycopg2 = "^2.9.21.20251012"
flake8 = "^7.3.0"
black = "^25.11.0"
isort = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
